import { useEffect, useMemo, useState } from "react";
import { amtCrossover, planYears, resolveLevers, runPlan, sweepIsoExercise, statusName, type Levers, type PlanResult, type Profile } from "@taxonomy/engine";
import { useProfile } from "./useProfile.ts";
import { Hero } from "./components/Hero.tsx";
import { LeverPanel } from "./components/Levers.tsx";
import { TaxStrip, CreditStrip } from "./components/Strips.tsx";
import { SweepChart } from "./components/SweepChart.tsx";
import { LedgerTable } from "./components/LedgerTable.tsx";
import { ExplainPanel } from "./components/ExplainPanel.tsx";

export interface Pinned { levers: Levers; plan: PlanResult; }
export interface Selection { year: number; id: string; }

export function App() {
  const state = useProfile();
  if (!state) return <div className="empty">Loading profile…</div>;
  if (!state.profile) return <div className="empty"><div className="error">{state.error}</div></div>;
  return <Workspace key={state.path} profile={state.profile} path={state.path} error={state.error} />;
}

function Workspace({ profile, path, error }: { profile: Profile; path: string; error: string | null }) {
  const years = planYears(profile);
  const [levers, setLevers] = useState<Levers>(() => resolveLevers(profile));
  const [focusYear, setFocusYear] = useState(years[0]!);
  const [pinned, setPinned] = useState<Pinned | null>(null);
  const [selected, setSelected] = useState<Selection | null>(null);

  // Keep the focus year valid if the plan window changes in the file.
  useEffect(() => { if (!years.includes(focusYear)) setFocusYear(years[0]!); }, [years.join(","), focusYear]);

  const plan = useMemo(() => runPlan(profile, levers), [profile, levers]);
  const crossovers = useMemo(() => years.map((y) => amtCrossover(profile, levers, y)), [profile, levers, years.join(",")]);
  const sweep = useMemo(() => sweepIsoExercise(profile, levers, focusYear, 40), [profile, levers, focusYear]);
  const focusCrossover = crossovers.find((c) => c.year === focusYear)!;

  const setExercise = (year: number, shares: number) =>
    setLevers((l) => ({ ...l, isoExercises: { ...l.isoExercises, [year]: Math.max(0, Math.round(shares)) } }));

  return (
    <div className={"app" + (selected ? " has-explain" : "")}>
      <header className="topbar">
        <h1>Taxonomy</h1>
        <span className="chip">{statusName(profile.filer.filingStatus)} · {profile.filer.state}</span>
        <span className="chip">{years[0]}–{years[years.length - 1]}</span>
        <span className="chip" title="Edit this file; the app follows it">{path}</span>
        <span className="spacer" />
        <button className="btn" onClick={() => setLevers(resolveLevers(profile))}>Reset levers</button>
        {pinned
          ? <button className="btn" onClick={() => setPinned(null)}>Unpin</button>
          : <button className="btn primary" onClick={() => setPinned({ levers, plan })}>Pin this scenario</button>}
      </header>

      <aside className="sidebar">
        <LeverPanel profile={profile} levers={levers} crossovers={crossovers} focusYear={focusYear} onFocus={setFocusYear} onChange={setExercise} />
      </aside>

      <main className="main">
        {error && <div className="error">Profile file has a problem; showing the last good version.{"\n"}{error}</div>}
        <Hero plan={plan} pinned={pinned?.plan ?? null} years={years} />
        <section className="card">
          <h2>Tax by year</h2>
          <div className="sub">Click a year to focus it. {pinned ? "Gray columns are the pinned scenario." : ""}</div>
          <TaxStrip plan={plan} pinned={pinned?.plan ?? null} focusYear={focusYear} onFocus={setFocusYear} />
        </section>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))", gap: 22 }}>
          <section className="card">
            <h2>AMT credit bank</h2>
            <div className="sub">Credit generated by ISO exercises, waiting to offset regular tax in later years.</div>
            <CreditStrip plan={plan} pinned={pinned?.plan ?? null} focusYear={focusYear} onFocus={setFocusYear} />
          </section>
          <section className="card">
            <h2>AMT in {focusYear} vs shares exercised</h2>
            <div className="sub">Holding the other years fixed. The marker is where AMT starts.</div>
            <SweepChart sweep={sweep} crossover={focusCrossover} current={levers.isoExercises[focusYear] ?? 0} onChange={(n) => setExercise(focusYear, n)} />
          </section>
        </div>
        <section className="card">
          <h2>Ledger</h2>
          <div className="sub">Click any number for the reason behind it.</div>
          <LedgerTable plan={plan} pinned={pinned?.plan ?? null} focusYear={focusYear} selected={selected} onSelect={setSelected} />
        </section>
      </main>

      {selected && (
        <aside className="explain">
          <ExplainPanel plan={plan} pinned={pinned?.plan ?? null} selection={selected} onSelect={setSelected} onClose={() => setSelected(null)} />
        </aside>
      )}
    </div>
  );
}
